import sqlite3

# connect to db & create it if not already made
connection = sqlite3.connect("pokedex.db")

# Create cursor to manipulate db
cursor = connection.cursor()

# Create pokemon data table
cursor.execute('''
CREATE TABLE IF NOT EXISTS pokemon(
    master_id INT NOT NULL PRIMARY KEY,
    species TEXT, 
    type1 TEXT,
    type2 TEXT,
    feet INT,
    inches INT,
    weight REAL,
    pokedex_entry TEXT 
)
''')

# Insert pokemon data
cursor.execute('''
INSERT INTO pokemon(master_id, species, type1, type2, feet, inches, weight, pokedex_entry)               
VALUES
(1, 'bulbasaur', 'grass', 'poison', 2, 4, 15.2, 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.'),
(2, 'ivysaur', 'grass', 'poison', 3, 3, 28.7, 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.'),
(3, 'venusaur', 'grass', 'poison', 6, 7, 220.5, 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.'),
(4, 'charmander', 'fire', NULL, 2, 0, 18.7, 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.'),
(5, 'charmeleon', 'fire', NULL, 3, 7, 41.9, 'When it swings its burning tail, it elevates the temperature to unbearably high levels.'),
(6, 'charizard', 'fire', 'flying', 5, 7, 199.5, 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.'),
(7, 'squirtle', 'water', NULL, 1, 8, 19.8, 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.'),
(8, 'wartortle', 'water', NULL, 3, 3, 49.6, 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.'),
(9, 'blastoise', 'water', NULL, 5, 3, 188.5, 'A brutal Pokémon with pressurized water jets on its shell. They are used for high-speed tackles.'),

(10, 'caterpie', 'bug', NULL, 1, 0, 6.4, 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.'),
(11, 'metapod', 'bug', NULL, 2, 4, 21.8, 'This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.'),
(12, 'butterfree', 'bug', 'flying', 3, 7, 70.5, 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.'),
(13, 'weedle', 'bug', 'poison', 1, 0, 7.1, 'Often found in forests, eating leaves. It has a sharp stinger on its head that injects poison.'),
(14, 'kakuna', 'bug', 'poison', 2, 0, 22.0, 'Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.'),
(15, 'beedrill', 'bug', 'poison', 3, 3, 65.0, 'Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.'),
(16, 'pidgey', 'normal', 'flying', 1, 0, 4.0, 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.'),
(17, 'pidgeotto', 'normal', 'flying', 3, 7, 66.1, 'Very protective of its sprawling territory, this Pokémon will fiercely peck at any intruder.'),
(18, 'pidgeot', 'normal', 'flying', 4, 11, 87.1, 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.'),
(19, 'rattata', 'normal', NULL, 1, 0, 7.7, 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.'),
(20, 'raticate', 'normal', NULL, 2, 4, 40.8, 'It uses its whiskers to maintain its balance. It seems to slow down if they are cut off.'),
(21, 'spearow', 'normal', 'flying', 1, 0, 4.4, 'Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.'),
(22, 'fearow', 'normal', 'flying', 3, 11, 83.8, 'With its huge and magnificent wings, it can keep aloft without ever having to land for rest.'),
(23, 'ekans', 'poison', NULL, 6, 7, 15.2, 'Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.'),
(24, 'arbok', 'poison', NULL, 11, 6, 143.3, 'The frightening patterns on its belly have been studied. Six variations have been confirmed.'),
(25, 'pikachu', 'electric', NULL, 1, 4, 13.2, 'When several of these Pokémon gather, their electricity could build and cause lightning storms.'),
(26, 'raichu', 'electric', NULL, 2, 7, 66.1, 'Its long tail serves as a ground to protect itself from its own high-voltage power.'),
(27, 'sandshrew', 'ground', NULL, 2, 0, 26.5, 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.'),
(28, 'sandslash', 'ground', NULL, 3, 3, 65.0, 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.'),
(29, 'nidoran♀', 'poison', NULL, 1, 4, 15.4, 'Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.'),
(30, 'nidorina', 'poison', NULL, 2, 7, 44.1, 'The female''s horn develops slowly. Prefers physical attacks such as clawing and biting.'),
(31, 'nidoqueen', 'poison', 'ground', 4, 3, 132.3, 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.'),
(32, 'nidoran♂', 'poison', NULL, 1, 8, 19.8, 'Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.'),
(33, 'nidorino', 'poison', NULL, 2, 11, 43.0, 'Its horn contains venom. If it stabs an enemy with the horn, the impact makes the poison leak out.'),
(34, 'nidoking', 'poison', 'ground', 4, 7, 136.7, 'It uses its powerful tail in battle to smash, constrict, then break the prey''s bones.'),
(35, 'clefairy', 'fairy', NULL, 2, 0, 16.5, 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.'),
(36, 'clefable', 'fairy', NULL, 4, 3, 88.2, 'A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people.'),
(37, 'vulpix', 'fire', NULL, 2, 0, 21.8, 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.'),
(38, 'ninetales', 'fire', NULL, 3, 7, 43.9, 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1,000-year curse.'),
(39, 'jigglypuff', 'fairy', NULL, 1, 8, 12.1, 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.'),
(40, 'wigglytuff', 'fairy', NULL, 3, 3, 26.5, 'Its body is full of elasticity. By inhaling deeply, it can continue to inflate itself without limit.'),

(41, 'zubat', 'poison', 'flying', 2, 7, 16.5, 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.'),
(42, 'golbat', 'poison', 'flying', 5, 3, 121.3, 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.'),
(43, 'oddish', 'grass', 'poison', 1, 8, 11.9, 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.'),
(44, 'gloom', 'grass', 'poison', 2, 7, 19.0, 'The fluid that oozes from its mouth isn''t drool. It is a nectar that is used to attract prey.'),
(45, 'vileplume', 'grass', 'poison', 3, 11, 41.0, 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.'),
(46, 'paras', 'bug', 'grass', 1, 0, 11.9, 'Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.'),
(47, 'parasect', 'bug', 'grass', 3, 3, 65.0, 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.'),
(48, 'venonat', 'bug', 'poison', 3, 3, 66.1, 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.'),
(49, 'venomoth', 'bug', 'poison', 4, 11, 27.6, 'The powdery scales on its wings are hard to remove. They also contain poison that leaks out on contact.'),
(50, 'diglett', 'ground', NULL, 0, 8, 1.8, 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.'),
(51, 'dugtrio', 'ground', NULL, 2, 4, 73.4, 'A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.'),
(52, 'meowth', 'normal', NULL, 1, 4, 9.3, 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.'),
(53, 'persian', 'normal', NULL, 3, 3, 70.5, 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.'),
(54, 'psyduck', 'water', NULL, 2, 7, 43.2, 'While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.'),
(55, 'golduck', 'water', NULL, 5, 7, 168.9, 'Often seen swimming elegantly by lakeshores. It is often mistaken for the Japanese monster, Kappa.'),
(56, 'mankey', 'fighting', NULL, 1, 8, 61.7, 'Extremely quick to anger. It could be docile one moment, then thrashing away the next instant.'),
(57, 'primeape', 'fighting', NULL, 3, 3, 70.5, 'Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.'),
(58, 'growlithe', 'fire', NULL, 2, 4, 41.9, 'Very protective of its territory. It will bark and bite to repel intruders from its space.'),
(59, 'arcanine', 'fire', NULL, 6, 3, 341.7, 'A Pokémon that has been admired since the past for its beauty. It runs gracefully, as if on wings.'),
(60, 'poliwag', 'water', NULL, 2, 0, 27.3, 'Its newly grown legs prevent it from walking well. It appears to prefer swimming over walking.'),
(61, 'poliwhirl', 'water', NULL, 3, 3, 44.1, 'Capable of living in or out of water. When out of water, it sweats to keep its body slimy.'),
(62, 'poliwrath', 'water', 'fighting', 4, 3, 119.0, 'An adept swimmer at both the front crawl and breaststroke. Easily overtakes the best human swimmers.'),
(63, 'abra', 'psychic', NULL, 2, 11, 43.0, 'Using its ability to read minds, it will identify impending danger and teleport to safety.'),
(64, 'kadabra', 'psychic', NULL, 4, 3, 124.6, 'It emits special alpha waves from its body that induce headaches just by being close by.'),
(65, 'alakazam', 'psychic', NULL, 4, 11, 105.8, 'Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000.'),
(66, 'machop', 'fighting', NULL, 2, 7, 43.0, 'Loves to build its muscles. It trains in all styles of martial arts to become even stronger.'),
(67, 'machoke', 'fighting', NULL, 4, 11, 155.4, 'Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.'),
(68, 'machamp', 'fighting', NULL, 5, 3, 286.6, 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.'),
(69, 'bellsprout', 'grass', 'poison', 2, 4, 8.8, 'A carnivorous Pokémon that traps and eats bugs. It appears to use its root feet to replenish moisture.'),
(70, 'weepinbell', 'grass', 'poison', 3, 3, 14.1, 'It spits out poison powder to immobilize the enemy and then finishes it with a spray of acid.'),
               
(71, 'victreebel', 'grass', 'poison', 5, 7, 34.2, 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.'),
(72, 'tentacool', 'water', 'poison', 2, 11, 100.3, 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stingers.'),
(73, 'tentacruel', 'water', 'poison', 5, 3, 121.3, 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.'),
(74, 'geodude', 'rock', 'ground', 1, 4, 44.1, 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.'),
(75, 'graveler', 'rock', 'ground', 3, 3, 231.5, 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.'),
(76, 'golem', 'rock', 'ground', 4, 7, 661.4, 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.'),
(77, 'ponyta', 'fire', NULL, 3, 3, 66.1, 'Its hooves are ten times harder than diamond. It can trample anything completely flat in little time.'),
(78, 'rapidash', 'fire', NULL, 5, 7, 209.4, 'Just loves to run. If it sees something faster than itself, it will give chase at top speed.'),
(79, 'slowpoke', 'water', 'psychic', 3, 11, 79.4, 'Incredibly slow and dopey. It takes five seconds for it to feel pain when under attack.'),
(80, 'slowbro', 'water', 'psychic', 5, 3, 173.1, 'The Shellder that is latched onto Slowpoke''s tail is said to feed on the host''s leftover scraps.'),
(81, 'magnemite', 'electric', 'steel', 1, 0, 13.2, 'Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves.'),
(82, 'magneton', 'electric', 'steel', 3, 3, 132.3, 'Formed by several Magnemite linked together. They frequently appear when sunspots flare up.'),
(83, 'farfetchd', 'normal', 'flying', 2, 7, 33.1, 'The plant stalk it holds is its weapon. The stalk is used like a sword to cut all sorts of things.'),
(84, 'doduo', 'normal', 'flying', 4, 7, 86.4, 'A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.'),
(85, 'dodrio', 'normal', 'flying', 5, 11, 187.8, 'Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.'),
(86, 'seel', 'water', NULL, 3, 7, 198.4, 'The protruding horn on its head is very hard. It is used for bashing through thick ice.'),
(87, 'dewgong', 'water', 'ice', 5, 7, 264.6, 'Stores thermal energy in its body. Swims at a steady eight knots even in intensely cold waters.'),
(88, 'grimer', 'poison', NULL, 2, 11, 66.1, 'Appears in filthy areas. It thrives by sucking up polluted sludge that is pumped out of factories.'),
(89, 'muk', 'poison', NULL, 3, 11, 66.1, 'Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.'),
(90, 'shellder', 'water', NULL, 1, 0, 8.8, 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.'),
(91, 'cloyster', 'water', 'ice', 4, 11, 292.1, 'Its shell is extremely hard. It cannot be shattered, even with a bomb. The shell opens only when it is attacking.'),
(92, 'gastly', 'ghost', 'poison', 4, 3, 0.2, 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.'),
(93, 'haunter', 'ghost', 'poison', 5, 3, 0.2, 'By licking, it saps the victim''s life. It causes shaking that won''t stop until the victim''s demise.'),
(94, 'gengar', 'ghost', 'poison', 4, 11, 89.3, 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.'),
(95, 'onix', 'rock', 'ground', 28, 10, 463.0, 'As it grows, the stone portions of its body harden to become similar to black diamonds.'),
(96, 'drowzee', 'psychic', NULL, 3, 3, 71.4, 'Puts enemies to sleep, then eats their dreams. Occasionally gets sick from eating bad dreams.'),
(97, 'hypno', 'psychic', NULL, 5, 3, 166.7, 'When it locks eyes with an enemy, it uses a mix of PSI moves such as Hypnosis and Confusion.'),
(98, 'krabby', 'water', NULL, 1, 4, 14.3, 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.'),
(99, 'kingler', 'water', NULL, 4, 3, 132.3, 'The large pincer has 10,000-horsepower strength. However, it is so heavy, it is difficult to aim.'),
(100, 'voltorb', 'electric', NULL, 1, 8, 22.9, 'Usually found in power plants. Easily mistaken for a Poké Ball, it has zapped many people.'),
               
(101, 'electrode', 'electric', NULL, 3, 11, 146.8, 'It stores electric energy under very high pressure. It often explodes with little or no provocation.'),
(102, 'exeggcute', 'grass', 'psychic', 1, 4, 5.5, 'Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.'),
(103, 'exeggutor', 'grass', 'psychic', 6, 7, 264.6, 'Its three heads think independently. However, they are friendly and never appear to squabble.'),
(104, 'cubone', 'ground', NULL, 1, 4, 14.3, 'Because it never removes its skull helmet, no one has ever seen this Pokémon''s real face.'),
(105, 'marowak', 'ground', NULL, 3, 3, 99.2, 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.'),
(106, 'hitmonlee', 'fighting', NULL, 4, 11, 109.8, 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.'),
(107, 'hitmonchan', 'fighting', NULL, 4, 7, 110.7, 'While apparently doing nothing, it fires punches in lightning-fast volleys that are impossible to see.'),
(108, 'lickitung', 'normal', NULL, 3, 11, 144.4, 'Its tongue can be extended like a chameleon''s. It leaves a tingling sensation when it licks enemies.'),
(109, 'koffing', 'poison', NULL, 2, 0, 2.2, 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.'),
(110, 'weezing', 'poison', NULL, 3, 11, 20.9, 'Where two kinds of poison gases meet, two Koffing can fuse into a Weezing over many years.'),
(111, 'rhyhorn', 'ground', 'rock', 3, 3, 253.5, 'Its massive bones are 1,000 times harder than human bones. It can easily knock a trailer flying.'),
(112, 'rhydon', 'ground', 'rock', 6, 3, 264.6, 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees Fahrenheit.'),
(113, 'chansey', 'normal', NULL, 3, 7, 76.3, 'A rare and elusive Pokémon that is said to bring happiness to those who manage to get it.'),
(114, 'tangela', 'grass', NULL, 3, 3, 77.2, 'The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.'),
(115, 'kangaskhan', 'normal', NULL, 7, 3, 176.4, 'The infant rarely ventures out of its mother''s protective pouch until it is 3 years old.'),
(116, 'horsea', 'water', NULL, 1, 4, 17.6, 'Known to shoot down flying bugs with precision blasts of ink from the surface of the water.'),
(117, 'seadra', 'water', NULL, 3, 11, 55.1, 'Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.'),
(118, 'goldeen', 'water', NULL, 2, 0, 33.1, 'Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.'),
(119, 'seaking', 'water', NULL, 4, 3, 86.0, 'In the autumn, its body becomes more fatty in preparing to propose to a mate. It takes on beautiful colors.'),
(120, 'staryu', 'water', NULL, 2, 7, 76.1, 'An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle.'),
(121, 'starmie', 'water', 'psychic', 3, 7, 176.4, 'Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.'),
(122, 'mr. mime', 'psychic', 'fairy', 4, 3, 120.2, 'If interrupted while it is miming, it will slap around the offender with its broad hands.'),
(123, 'scyther', 'bug', 'flying', 4, 11, 123.5, 'With ninja-like agility and speed, it can create the illusion that there are more than one.'),
(124, 'jynx', 'ice', 'psychic', 4, 7, 89.5, 'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.'),
(125, 'electabuzz', 'electric', NULL, 3, 7, 66.1, 'Normally found near power plants, they can wander away and cause major blackouts in cities.'),
(126, 'magmar', 'fire', NULL, 4, 3, 98.1, 'Its body always burns with an orange glow that enables it to hide perfectly among flames.'),
(127, 'pinsir', 'bug', NULL, 4, 11, 121.3, 'If it fails to crush the victim in its pincers, it will swing it around and toss it hard.'),
(128, 'tauros', 'normal', NULL, 4, 7, 194.9, 'When it targets an enemy, it charges furiously while whipping its body with its long tails.'),
(129, 'magikarp', 'water', NULL, 2, 11, 22.0, 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.'),
(130, 'gyarados', 'water', 'flying', 21, 4, 518.1, 'Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.'),

(131, 'lapras', 'water', 'ice', 8, 2, 485.0, 'A Pokémon that has been overhunted almost to extinction. It can ferry people across the water.'),
(132, 'ditto', 'normal', NULL, 1, 0, 8.8, 'Capable of copying an opponent''s genetic code to instantly transform itself into a duplicate of the enemy.'),
(133, 'eevee', 'normal', NULL, 1, 0, 14.3, 'Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.'),
(134, 'vaporeon', 'water', NULL, 3, 3, 63.9, 'Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid''s.'),
(135, 'jolteon', 'electric', NULL, 2, 7, 54.0, 'It accumulates negative ions in the atmosphere to blast out 10,000-volt lightning bolts.'),
(136, 'flareon', 'fire', NULL, 2, 11, 55.1, 'When storing thermal energy in its body, its temperature can soar to over 1,600 degrees Fahrenheit.'),
(137, 'porygon', 'normal', NULL, 2, 7, 80.5, 'A man-made Pokémon that came about as a result of research. It is programmed with only basic motions.'),
(138, 'omanyte', 'rock', 'water', 1, 4, 16.5, 'Although long extinct, in rare cases, it can be genetically resurrected from fossils.'),
(139, 'omastar', 'rock', 'water', 3, 3, 77.2, 'A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey.'),
(140, 'kabuto', 'rock', 'water', 1, 8, 25.4, 'A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago.'),
(141, 'kabutops', 'rock', 'water', 4, 3, 89.3, 'Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.'),
(142, 'aerodactyl', 'rock', 'flying', 5, 11, 130.1, 'A ferocious, prehistoric Pokémon that goes for the enemy''s throat with its serrated, saw-like fangs.'),
(143, 'snorlax', 'normal', NULL, 6, 11, 1014.1, 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.'),
(144, 'articuno', 'ice', 'flying', 5, 7, 122.1, 'A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains.'),
(145, 'zapdos', 'electric', 'flying', 5, 3, 116.0, 'A legendary Pokémon that is said to appear from clouds while dropping enormous lightning bolts.'),
(146, 'moltres', 'fire', 'flying', 6, 7, 132.3, 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flare of flames.'),
(147, 'dratini', 'dragon', NULL, 5, 11, 7.3, 'Long considered a mythical Pokémon until recently when a small colony was found living underwater.'),
(148, 'dragonair', 'dragon', NULL, 13, 1, 36.4, 'A mystical Pokémon that exudes a gentle aura. It is said to have the ability to change the weather.'),
(149, 'dragonite', 'dragon', 'flying', 7, 3, 463.0, 'An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.'),
(150, 'mewtwo', 'psychic', NULL, 6, 7, 269.0, 'It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.'),
(151, 'mew', 'psychic', NULL, 1, 4, 8.8, 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.')     
''')

# Commit changes
connection.commit()

# Close connection with database
connection.close()
